---
abstract: 'Perl extension to communicate with Glimpse server'
author:
  - 'Alberto Simões <ambs@cpan.org>'
build_requires:
  Test::Pod: 1.00
  Test::Pod::Coverage: 0.08
configure_requires:
  Config::AutoConf: 0.14
  Module::Build: 0.3603
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-Glimpse
provides:
  Search::Glimpse:
    file: lib/Search/Glimpse.pm
    version: 0.03
requires:
  IO::File: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
