# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Glimpse
version:      0.02
version_from: lib/Search/Glimpse.pm
installdirs:  site
requires:
    IO::File:                      0
    Test::Pod:                     1
    Test::Pod::Coverage:           0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
